Update Model for DG
AY2324S1-CS2103T-F08-3/tp pull request #90
Opened 2023-10-27 07:14 UTC by Blizzeracz

2023-10-27 11:05 UTC, euchangxian requested changes

2023-10-27 11:05 UTC, euchangxian commented on docs/diagrams/BetterModelClassDiagram.puml
> +AddressBook *-right-> "1" UniquePetIdList
Should be a mistake here; Do fix it

2023-10-28 12:20 UTC, Blizzeracz commented on docs/diagrams/BetterModelClassDiagram.puml
> +AddressBook *-right-> "1" UniquePetIdList
Yep, Thank you

2023-10-28 12:21 UTC, Blizzeracz commented on docs/diagrams/ModelClassDiagram.puml
> +Class Catalog
Yep thats right

2023-10-28 12:26 UTC, Blizzeracz commented on docs/DeveloperGuide.md
> +**Note:** An alternative (arguably, a more OOP) model is given below. It has a `PetId` list in the `Catalog`, which `Animal` can reference. This allows `Catalog` to only require `PetId` object, inste
It should be better to reflect the class name instead of using them interchangeably. ThankS!

2023-10-31 05:21 UTC, euchangxian approved these changes
LGTM. Thanks for making the requested changes!

2023-10-31 05:22 UTC, merged